### ISSUE TITLE
program line 204 problem

### ISSUE THREAD

**Issue by Barbercrew3809** [maxplayle04/MaxBot#17] opened 2020-07-07 20:36 UTC
needs investigation throwing error message off

**Comment by thatmaxplayle** [comment] 2020-07-07 20:36
****
![image](https://user-images.githubusercontent.com/63079841/86839877-e6a00f00-c099-11ea-9446-c97d072de069.png)

**Comment by thatmaxplayle** [comment] 2020-07-08 21:43
Bug fixed; due to a member of one (or more) servers containing members with "Nitro" in their name, for instance, (Nitro Model), Discord API doesn't like this! 

Part-changelog for 1.7.0 Beta:
`
- Fixed the weird bug on startup where an exception was caused by printing “Service has become available” messages to servers where a member had “Nitro” in their name.
`
This issue has been fixed; closing report. 

**Thank you for reporting this bug.**

**Closed as completed by thatmaxplayle** 2020-07-08 21:43 UTC
Labels: bug, easy implementation, code, on behalf, service, Addressed in recent update
